New Project generation feature
nasa/fprime-tools pull request #124
Opened 2023-04-06 01:49 UTC by thomas-bc

| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

Adds in a new project cookiecutter template and the associated logic for `new --project`
Checks that git is installed, generates a minimal amount of project files, then init a git repo and add F' as a git submodule.
Optionally creates a venv and sets it up with requirements.txt.

## Rationale

Vastly improves user experience to getting started, enforces a good project structure instead of using `Ref/`

## Testing/Review Recommendations

```
fprime-util new --project
cd ...
fprime-util new --deployment
cd ...
fprime-util generate
fprime-util build
fprime-gds
```
Tested with `pip install .` with no -e.

2023-04-06 01:50 UTC, thomas-bc commented
@LeStarch  There's probably a lot to be said about the generated `CMakeLists.txt` and `settings.ini` as this methodology is not clearly defined yet. Should we just remove them for the time being?

2023-04-06 01:57 UTC, thomas-bc commented on src/fprime/cookiecutter_templates/cookiecutter-fprime-project/hooks/post_gen_project.py
> +if ("{{cookiecutter.install_venv}}" == "yes"):
False positive, `{{cookiecutter.install_venv}}` is not actually a constant since it can be set by the user.

2023-04-06 01:57 UTC, thomas-bc commented on src/fprime/cookiecutter_templates/cookiecutter-fprime-project/hooks/post_gen_project.py
> +if ("{{cookiecutter.install_venv}}" == "yes"):
False positive, `{{cookiecutter.install_venv}}` is not actually a constant since it can be set by the user.

2023-04-13 18:40 UTC, LeStarch requested changes

2023-04-13 18:40 UTC, LeStarch commented on src/fprime/cookiecutter_templates/cookiecutter-fprime-project/hooks/post_gen_project.py
> +Windows: venv\Scripts\\activate.bat
Remove this windows line for the timebeing.

2023-04-13 18:40 UTC, LeStarch commented on src/fprime/cookiecutter_templates/cookiecutter-fprime-project/hooks/post_gen_project.py
> +-- Run the base deployment --
Remove "Run base deployment"

2023-04-13 22:10 UTC, LeStarch approved these changes

2023-04-13 22:10 UTC, merged