Fix #130
nasa/fprime-tools pull request #136
Opened 2023-05-02 17:23 UTC by stepanzubkov

Just remove unused variable

2023-05-02 18:21 UTC, ThibFrgsGmz commented
You can put in the title the hyperlink to the issue, it will render the same but with a link to directly access the ticket 😀

2023-05-03 00:08 UTC, thomas-bc requested changes

2023-05-03 00:08 UTC, thomas-bc commented on src/fprime/util/string_util.py
> +    except ValueError:
It seems there is this exact pattern that's used [a couple lines below](https://github.com/fprime-community/fprime-tools/blob/53ccc63bc241c3a902e7d5c114fcf85d5ae178cf/src/fprime/util/string_util.py#L110), we should probably keep it consistent. Would you mind making that change as well?

2023-05-03 00:13 UTC, thomas-bc commented on src/fprime/util/string_util.py
> +    except ValueError:
Oh wait I may have spoken too fast, we're raising it up in that second case.
https://github.com/fprime-community/fprime-tools/blob/6d258007391e9a4091b29b0af3ba6ef13c798f5b/src/fprime/util/string_util.py#L116

2023-05-03 00:17 UTC, thomas-bc commented on src/fprime/util/string_util.py
> +    except ValueError:
Annnd we're actually using the exception...
https://github.com/fprime-community/fprime-tools/blob/6d258007391e9a4091b29b0af3ba6ef13c798f5b/src/fprime/util/string_util.py#L114
Read tgat way too fast lol, my apologies. This looks good to me.

2023-05-03 00:17 UTC, thomas-bc approved these changes
LGTM

2023-05-03 01:10 UTC, ThibFrgsGmz commented
The title update did not worked ? 🤔
At least in the description it would work.

2023-05-03 16:23 UTC, merged