Add pyproject.toml
nasa/fprime-tools pull request #181
Opened 2023-12-06 19:47 UTC by thomas-bc

| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**| https://github.com/nasa/fprime/issues/1995 |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

- Add `pyproject.toml` 
- Remove legacy `setup.py`
- Update publishing workflow to use trusted publishers mechanism

## Rationale

Conform to PEP517, 518 et al. Modernize our Python setup so as not to be left behind. Potentially help with Python 3.12 support

## Testing/Review Recommendations

Alpha release and let CI fly. Tested in branch with test.pypi.org: https://github.com/fprime-community/fprime-tools/actions/runs/7119122735

2023-12-06 20:29 UTC, LeStarch requested changes
One comment in-line.  Additionally `setup.py` should now look like:

```
from setuptools import setup

setup()
```
As noted for backwards compatibility here: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

2023-12-06 20:29 UTC, LeStarch commented on .github/workflows/publish.yml
> +        run: pip3 install -U pip wheel build setuptools setuptools_scm twine
Don't we just need `build` and `twine` as it should detect the other necessary tools from the requires section.

2023-12-06 21:38 UTC, thomas-bc commented on .github/workflows/publish.yml
> +        run: pip3 install -U pip wheel build setuptools setuptools_scm twine
Good point

2023-12-07 19:31 UTC, LeStarch approved these changes, later dismissed
PY 12?  but not a blocker.

2023-12-13 23:13 UTC, LeStarch approved these changes

2023-12-13 23:14 UTC, merged