CR 2375: TimeType.to_readable should display microsecond precision.
nasa/fprime-tools pull request #197
Opened 2024-03-09 23:37 UTC by Ahmad-Bamba

| | |
|:---|:---|
|**_Related Issue(s)_**| [2375](https://github.com/nasa/fprime/issues/2375) |
|**_Has Unit Tests (y/n)_**| n |
|**_Documentation Included (y/n)_**| n  |

---
## Change Description

This change makes the TimeType.to_readable function use datetime.isoformat to convert the datetime object to a human readable format. In doing so, fprime-gds outputs `channel.log` entries with microsecond precision.

## Rationale

> The fundamental philosophy that must be applied to the ground system is that any conversion (time, DN->EU, units, etc.) should never decrease the resolution of the source data.

## Testing/Review Recommendations

I tested the changes locally by first following the [fprime hello world](https://fprime-community.github.io/fprime-tutorial-hello-world/) tutorial. Then I installed the local version of fprime-tools, and ran the example project with `fprime-gds`. This produced the following output that I've attached below showing no more accuracy loss in `channel.log`:

![image](https://github.com/fprime-community/fprime-tools/assets/5873587/e40f94b1-76bf-46a7-8aad-16abddc1bcc2)

Compared with before this change:

![image](https://github.com/fprime-community/fprime-tools/assets/5873587/591712d0-118f-4c5c-93b7-31071aafc3b4)

## Future Work

This seems like too a small change to make a unit test for, but I could think of a good way to design one if requested.

2024-03-10 02:11 UTC, thomas-bc requested changes
Looks good to me! Thank you!

Could we just force the timespec `dt.isoformat(timespec="microseconds")` ? Default seems to be `auto` which falls back to microseconds in our case, but you never know, and it's also easier to read/understand that way.

You're also going to need to [format the file](https://github.com/fprime-community/fprime-tools/tree/devel?tab=readme-ov-file#black-formatter) for it to pass CI, and add `isoformat` to https://github.com/fprime-community/fprime-tools/blob/devel/.github/actions/spelling/expect.txt for spelling

2024-03-10 19:28 UTC, Ahmad-Bamba commented
Feel free to let me know if there is anything else that can be done to improve this

2024-03-11 02:21 UTC, thomas-bc commented
@Ahmad-Bamba could you please also push the timespec="microseconds" change?

2024-03-11 02:50 UTC, Ahmad-Bamba commented
Ah, I neglected to actually git add that file. My bad

2024-03-11 02:56 UTC, Ahmad-Bamba commented
Should be good. Sorry about that!

2024-03-11 18:16 UTC, thomas-bc approved these changes

2024-03-11 18:18 UTC, thomas-bc commented
@LeStarch would you put a second set of eyes on this ?

2024-03-11 20:43 UTC, LeStarch approved these changes
This is a *great* solution.  Much better than what we had.  I confirmed that from Python 3.6 through 3.11 the documentation backs-up the change (this call is supported in all versions)!

2024-03-11 20:43 UTC, merged