Update library_locations for _fprime_packages
nasa/fprime-tools pull request #210
Opened 2024-07-24 18:16 UTC by mosa11aei

| | |
|:---|:---|
|**_Related Issue(s)_**| n |
|**_Has Unit Tests (y/n)_**| n |
|**_Documentation Included (y/n)_**| n/a |

---
## Change Description

Linked with https://github.com/nasa/fprime/pull/2812. Adds `_fprime_packages` to the settings.ini load.

2024-07-24 22:47 UTC, LeStarch requested changes

2024-07-24 22:47 UTC, LeStarch commented on src/fprime/fbuild/settings.py
> +        except FileNotFoundError:
Probably should fix this....add a comment

2024-07-25 17:58 UTC, LeStarch approved these changes

2024-08-01 18:18 UTC, thomas-bc approved these changes

2024-08-01 18:18 UTC, merged